version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Hasith456
      MYSQL_DATABASE: toDoAplication
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backEnd
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/toDoAplication
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hasith456

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontEnd
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
