version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Gr3atS3cur!ty_2025
      MYSQL_DATABASE: toDoAplication
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backEnd
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/toDoAplication
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gr3atS3cur!ty_2025

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontEnd
    ports:
      - "4200:80"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Gr3atS3cur!ty_2025
    depends_on:
      - db 

volumes:
  db_data:
